spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#tomcat:
#  ajp:
#    protocol: AJP/1.3
#    port: 8081
#    enabled: true

#  profiles:
#    include: mysql